version: '3'

services:
  web:
    build:
      context: ./  # Le chemin vers le répertoire de votre projet Django
      dockerfile: dockerfile  # Nom de votre Dockerfile
    ports:
      - "8000:8000"  # Mappez le port du conteneur à l'hôte
    environment:
      - DEBUG=True  # Configurez les variables d'environnement si nécessaire
