version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    image: daoudryad/dz-pieces-image
    ports:
      - "8008:8008"
    volumes:
      - .:/app
    command: python manage.py runserver 0.u b0.0.0:8008











