# Generated by Django 4.0.4 on 2022-05-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_offre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='Subject',
            new_name='Message',
        ),
        migrations.AlterField(
            model_name='offre',
            name='Prix_Proposé',
            field=models.IntegerField(),
        ),
    ]
