# Generated by Django 4.0.4 on 2022-05-06 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_rename_subject_offre_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='Addresse',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='Message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='Prix_Proposé',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='Téléphone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='Shop.product'),
        ),
    ]
