# Generated by Django 4.0.4 on 2022-05-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_userprofile_address_userprofile_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
