# Generated by Django 4.0.4 on 2022-05-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('dossard', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Email',
            field=models.EmailField(default='exe@exe.com', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Phone',
            field=models.CharField(default='+213', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Sex',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profil.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
