# Generated by Django 4.0.4 on 2023-10-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_joueur_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Joueur',
        ),
    ]
